Navbar and Footer Responsiveness
dsc-ateneo-de-manila-university/qwiklabs-finishers-ph pull request #7
Opened 2020-05-29 14:59 UTC by JDVariadic

2020-05-29 15:29 UTC, Hjkun77 requested changes
Please fix these changes first before merging

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +        <img src="assets/images/image 1.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +        <img src="assets/images/image 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +            <img src="assets/images/Ellipse 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +            <img src="assets/images/Ellipse 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +            <img src="assets/images/Ellipse 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +            <img src="assets/images/Ellipse 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +            <img src="assets/images/Ellipse 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +            <img src="assets/images/Ellipse 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +            <img src="assets/images/Ellipse 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +            <img src="assets/images/Ellipse 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +            <img src="assets/images/Ellipse 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +            <img src="assets/images/Ellipse 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +            <img src="assets/images/Ellipse 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +            <img src="assets/images/Ellipse 2.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/index.html
> +        <img src="assets/images/image 1.png" />
add `alt="..."`

2020-05-29 15:29 UTC, Hjkun77 commented on public/scripts/index.js
> +  const secondaryNav = document.querySelector('.navigation-secondary')
set this as global variable

2020-05-29 15:29 UTC, Hjkun77 commented on public/scripts/index.js
> +  const burger = document.querySelector('.burger')
set this as global variable

2020-05-29 15:29 UTC, Hjkun77 commented on public/scripts/index.js
> +  burger.addEventListener('click', () => {
remove this and add it as an onclick method in the html than an eventlistener

2020-05-29 15:29 UTC, Hjkun77 commented on public/scripts/index.js
> +navToggle()
call this function as an onclick in the html instead

2020-05-29 15:29 UTC, Hjkun77 commented on public/scripts/index.js
> +    console.log(secondaryNav)
remove console.log()

2020-05-29 15:29 UTC, Hjkun77 commented on public/scripts/index.js
> +    console.log('working')
remove console.log()

2020-06-11 13:34 UTC, Znarfois commented
Updated the index.html to have onclick instead of inside index.js @Hjkun77

2020-06-11 13:44 UTC, Hjkun77 requested changes
since simple lang naman yung function...let's make it like this na lang hehe

2020-06-11 13:44 UTC, Hjkun77 commented on public/scripts/index.js
> +const navToggle = () => {
`const navToggle = () => secondaryNav.classList.toggle('nav-display')`

2020-06-11 14:14 UTC, Znarfois approved these changes

2020-06-11 14:37 UTC, merged